package com.github.projetp1;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This class is used to get the localized messages
 * 
 * Auto-generated by Eclipse
 */
public class Messages
{
	
	/** The Constant BUNDLE_NAME. */
	private static final String BUNDLE_NAME = "com.github.projetp1.messages"; //$NON-NLS-1$

	/** The Constant RESOURCE_BUNDLE. */
	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

	/**
	 * Instantiates a new messages.
	 */
	private Messages()
	{
	}

	/**
	 * Gets the string associated with the key
	 *
	 * @param key the key
	 * @return the localized string
	 */
	public static String getString(String key)
	{
		try
		{
			return RESOURCE_BUNDLE.getString(key);
		}
		catch (MissingResourceException e)
		{
			return '!' + key + '!';
		}
	}
}
